name: arxiv-digest

on:
  # 手动触发：增加一个“是否发送邮件”的输入开关（默认 false）
  workflow_dispatch:
    inputs:
      send_email:
        description: "Send email for manual run?"
        required: false
        default: "true"
        type: choice
        options: ["false", "true"]

  # 定时触发：每天 19:00 UTC = 北京时间次日 03:00
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # 允许提交 docs
    env:
      TZ: Asia/Shanghai         # 站点/邮件时间戳按北京时间显示

    steps:
      - name: Checkout
        uses: actions/checkout@v4

# 之后到仓库 Settings → Pages：
#   - Source 选 “Deploy from a branch”
#   - Branch 选 main / docs
