name: CI

on:
  workflow_dispatch:

jobs:

  build-llm-token-ratelimit:
    name: Build and test LLM Token Ratelimit - Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.22.0
        os:
          - ubuntu-latest
    services:
      redis-node1:
        image: redis:6.2-alpine
        options: >-
          --entrypoint /bin/sh
          -c
          "redis-server --cluster-enabled yes --cluster-config-file nodes-node1.conf --cluster-node-timeout 5000 --port 6379"
        ports:
          - 6379:6379
      redis-node2:
        image: redis:6.2-alpine
        options: >-
          --entrypoint /bin/sh
          -c
          "redis-server --cluster-enabled yes --cluster-config-file nodes-node2.conf --cluster-node-timeout 5000 --port 6380"
        ports:
          - 6380:6380
      redis-node3:
        image: redis:6.2-alpine
        options: >-
          --entrypoint /bin/sh
          -c
          "redis-server --cluster-enabled yes --cluster-config-file nodes-node3.conf --cluster-node-timeout 5000 --port 6381"
        ports:
          - 6381:6381
    steps:

      - name: Setup Redis Cluster
        run: |
          sleep 10
          redis-cli --cluster create \
          127.0.0.1:6379 \
          127.0.0.1:6380 \
          127.0.0.1:6381 \
          --cluster-replicas 0
          redis-cli -h 127.0.0.1 -c -p 6379 cluster info
          redis-cli -h 127.0.0.1 -c -p 6379 cluster nodes
